classDiagram
    class Robot {

    }
    class Conveyor {

    }
    class Vector {
        +x: float
        +y: float
        +z: float
        +add(other: Vector): Vector
        +substract(other: Vector): Vector
        +multiply(scalar: float): Vector
        +divide(scalar: float): Vector
        +dot(other: Vector): float
        +cross(other: Vector): Vector
        +length(): float
        +normalize(): Vector
    }